"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['stack.py']
DATA_FILES = ['unipuke_512.png', 'uni_icon.icns']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'uni_icon.icns'
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'pyqt5'],
)
